//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gescom22
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GesDataContainer : DbContext
    {
        public GesDataContainer()
            : base("name=GesDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<DetailsCommande> DetailCommande { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Paiement> Paiement { get; set; }
        public virtual DbSet<Livraison> Livraison { get; set; }
    }
}
